### ISSUE TITLE
Script #1 isn't working

### ISSUE THREAD

**Issue by Baemir** [erikdubois/Mint-Y-Colora-Theme#1]
I edited it as instructed. Hexadecimal code, 6 characters, no hashtag. Tested it against GIMP, websites, etc and the code is correct. Yet when I run the script and generate the themes, it gives me the default pale blue every time.

**Comment by erikdubois** [comment]
Did you check if the script is an executable?

**Comment by erikdubois** [comment]
get the latest code and watch the latest tutorial at http://erikdubois.be

**Comment by Baemir** [comment]
Mysteriously worked after attempting it again today, even though the terminal output was the same. 

I actually think elementary OS has some issues with loading gtk themes properly.
